# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "virtio_pci" "virtio_scsi" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/5ad5ab03-ff05-45f0-9aaf-c8b8c3d68fd3";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/backups" =
    { device = "/dev/disk/by-uuid/5ad5ab03-ff05-45f0-9aaf-c8b8c3d68fd3";
      fsType = "btrfs";
      options = [ "subvol=@backups" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/178F-074F";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/5ad5ab03-ff05-45f0-9aaf-c8b8c3d68fd3";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/5ad5ab03-ff05-45f0-9aaf-c8b8c3d68fd3";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
