# Hyprlock configuration

# Source: https://github.com/hyprwm/hyprlock

general {
    disable_loading_bar = false
    grace = 5
    no_fade_in = false
    immediate_lock = false
}

input {
    enable_group = true
    kb_layout = us,ru
    kb_options = grp:alt_shift_toggle
    kb_model =
    kb_variant =
    kb_rules =
}

background {
    monitor =
    path = /home/zumuvik/Pictures/wallpapers/default.jpg
    blur_passes = 1
    blur_size = 10
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
    color = rgba(25, 20, 31, 1.0)
}

label {
    monitor =
    text = 
    color = rgba(255, 255, 255, 1.0)
    font_family = JetBrains Mono
    font_size = 100
    font_weight = 700
    position = 0, -100
    halign = center
    valign = center
}

datetime {
    monitor =
    format = %H:%M
    font_family = JetBrains Mono
    font_size = 100
    font_weight = 700
    color = rgba(255, 255, 255, 1.0)
    position = 0, 0
    halign = center
    valign = center
}

datetime {
    monitor =
    format = %d.%m.%Y
    font_family = JetBrains Mono
    font_size = 40
    font_weight = 400
    color = rgba(255, 255, 255, 0.5)
    position = 0, 80
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2
    inner_margin = 10, 5
    outer_margin = 0, 50
    border_radius = 10
    halign = center
    valign = center
    placeholder_text = password...
    font_family = JetBrains Mono
    font_size = 20
    fail_text = $FAIL
    fade_on_empty = true
    empty_color = rgba(255, 255, 255, 0.3)
    inner_color = rgba(30, 30, 46, 0.5)
    outer_color = rgba(0, 255, 100, 1.0)
    border_color = rgba(0, 255, 100, 1.0)
    font_color = rgba(255, 255, 255, 1.0)
}
